name: CI

on: [push, pull_request]

jobs:
  mac:
    name: macOS
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode 13.3
        run: sudo xcode-select -s /Applications/Xcode_13.3.app
      - name: Run tests
        run: make test-swift