name: Format

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  swift_format:
    name: swift-format
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode 13.3
        run: sudo xcode-select -s /Applications/Xcode_13.3.app
      - name: Install
        run: brew install swift-format
      - name: Format
        run: make format
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Run swift-format
          branch: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
